variable "project_name" {}
variable "region" {}
variable "vpc_cidr" {}
variable "pub_sub_az1_cidr" {}
variable "pub_sub_az2_cidr" {}
variable "pri_web_az1_cidr" {}
variable "pri_web_az2_cidr" {}
variable "pri_db_az1_cidr" {}
variable "pri_db_az2_cidr" {}